[2021-02-14 15:48:34,156] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: NDBC_51001.clean_and_load 2021-02-15T01:48:27.503212+00:00 [queued]>
[2021-02-14 15:48:34,161] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: NDBC_51001.clean_and_load 2021-02-15T01:48:27.503212+00:00 [queued]>
[2021-02-14 15:48:34,161] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-14 15:48:34,161] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-14 15:48:34,161] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-14 15:48:34,167] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): clean_and_load> on 2021-02-15T01:48:27.503212+00:00
[2021-02-14 15:48:34,169] {standard_task_runner.py:52} INFO - Started process 93750 to run task
[2021-02-14 15:48:34,177] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'NDBC_51001', 'clean_and_load', '2021-02-15T01:48:27.503212+00:00', '--job-id', '30', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ndbc_dag.py', '--cfg-path', '/var/folders/y8/ykx6qdr96dldyw_z287s5l580000gn/T/tmpno7544wl', '--error-file', '/var/folders/y8/ykx6qdr96dldyw_z287s5l580000gn/T/tmpz96yot56']
[2021-02-14 15:48:34,178] {standard_task_runner.py:77} INFO - Job 30: Subtask clean_and_load
[2021-02-14 15:48:34,209] {logging_mixin.py:104} INFO - Running <TaskInstance: NDBC_51001.clean_and_load 2021-02-15T01:48:27.503212+00:00 [running]> on host chriss-mbp.lan1
[2021-02-14 15:48:34,235] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=holloway.christopher.t@gmail.com
AIRFLOW_CTX_DAG_OWNER=chris
AIRFLOW_CTX_DAG_ID=NDBC_51001
AIRFLOW_CTX_TASK_ID=clean_and_load
AIRFLOW_CTX_EXECUTION_DATE=2021-02-15T01:48:27.503212+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-15T01:48:27.503212+00:00
[2021-02-14 15:48:34,588] {base.py:65} INFO - Using connection to: id: NDBC_51001. Host: localhost, Port: 5400, Schema: NDBC_51001DB, Login: chrisholloway, Password: None, extra: None
[2021-02-14 15:48:34,594] {dbapi.py:180} INFO - Running statement: INSERT INTO Detailed_Wave_Data_Table (significant_wave_height, swell_height, swell_period, wind_wave_period,
	 wind_wave_height, wind_wave_period, average_period) VALUES (%f, %f, %f, %f, %f, %f, %f);, parameters: (2.9, 2.9, 13.8, 4.8, 0.6, 4.8, 9.5)
[2021-02-14 15:48:34,595] {taskinstance.py:1455} ERROR - unsupported format character 'f' (0x66) at index 172
Traceback (most recent call last):
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/chrisholloway/airflow/dags/ndbc_dag.py", line 52, in clean_load_data
    pg_hook.run(insert_cmd, parameters=row)
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 182, in run
    cur.execute(sql_statement, parameters)
ValueError: unsupported format character 'f' (0x66) at index 172
[2021-02-14 15:48:34,597] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=NDBC_51001, task_id=clean_and_load, execution_date=20210215T014827, start_date=20210215T014834, end_date=20210215T014834
[2021-02-14 15:48:34,621] {local_task_job.py:146} INFO - Task exited with return code 1
