[2021-02-14 15:05:18,608] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: NDBC_51001.clean_and_load 2021-02-15T01:05:10.628350+00:00 [queued]>
[2021-02-14 15:05:18,613] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: NDBC_51001.clean_and_load 2021-02-15T01:05:10.628350+00:00 [queued]>
[2021-02-14 15:05:18,613] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-14 15:05:18,613] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-14 15:05:18,614] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-14 15:05:18,620] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): clean_and_load> on 2021-02-15T01:05:10.628350+00:00
[2021-02-14 15:05:18,622] {standard_task_runner.py:52} INFO - Started process 90750 to run task
[2021-02-14 15:05:18,630] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'NDBC_51001', 'clean_and_load', '2021-02-15T01:05:10.628350+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ndbc_dag.py', '--cfg-path', '/var/folders/y8/ykx6qdr96dldyw_z287s5l580000gn/T/tmph_r9cmh0', '--error-file', '/var/folders/y8/ykx6qdr96dldyw_z287s5l580000gn/T/tmpz53ytmft']
[2021-02-14 15:05:18,631] {standard_task_runner.py:77} INFO - Job 7: Subtask clean_and_load
[2021-02-14 15:05:18,664] {logging_mixin.py:104} INFO - Running <TaskInstance: NDBC_51001.clean_and_load 2021-02-15T01:05:10.628350+00:00 [running]> on host chriss-mbp.lan1
[2021-02-14 15:05:18,683] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=holloway.christopher.t@gmail.com
AIRFLOW_CTX_DAG_OWNER=chris
AIRFLOW_CTX_DAG_ID=NDBC_51001
AIRFLOW_CTX_TASK_ID=clean_and_load
AIRFLOW_CTX_EXECUTION_DATE=2021-02-15T01:05:10.628350+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-15T01:05:10.628350+00:00
[2021-02-14 15:05:19,031] {utils.py:141} INFO - NumExpr defaulting to 8 threads.
[2021-02-14 15:05:19,040] {taskinstance.py:1455} ERROR - name 'api_date' is not defined
Traceback (most recent call last):
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/chrisholloway/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/chrisholloway/airflow/dags/ndbc_dag.py", line 46, in clean_load_data
    row = (api_date, sample_date, significant_wave_height, swell_height, swell_period, wind_wave_period,
NameError: name 'api_date' is not defined
[2021-02-14 15:05:19,042] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=NDBC_51001, task_id=clean_and_load, execution_date=20210215T010510, start_date=20210215T010518, end_date=20210215T010519
[2021-02-14 15:05:19,075] {local_task_job.py:146} INFO - Task exited with return code 1
